BOT_TOKEN = '0123456789:ABCDEFGHIJKLMNOPQRS'
TELEGRAM_API = 12345678, 'abcdefabcdefabcdefabcdef'
SPOTIFY_API = 'abcdefabcdefabcdefabcdef', 'abcdefabcdefabcdefabcdef'
DOMAIN = 'https://example.com/'
DATABASE = 'sqlite:///db.sqlite'
