"""init

Revision ID: 0234561abac9
Revises: 
Create Date: 2022-07-15 16:28:34.710493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0234561abac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('followers_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('telegramgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('photo_url', sa.String(length=256), nullable=True),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artists.id'], name='fk_artists_genres_artists_artist_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_artists_genres_genres_genre_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegramgroups_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('telegramgroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telegramgroup'], ['telegramgroups.id'], name='fk_telegramgroups_users_telegramgroups_telegramgroup_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_telegramgroups_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_x_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artists.id'], name='fk_users_x_artists_artists_artist_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_x_artists_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_x_artists')
    op.drop_table('telegramgroups_users')
    op.drop_table('artists_genres')
    op.drop_table('users')
    op.drop_table('telegramgroups')
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
